### ISSUE TITLE
Milestone 2 Todo list

### ISSUE THREAD

**Issue by KangboLu** [UBC-MDS/DSCI_522_Group_34#18]
- [x] download_data.py: same as download_data.R but it's written in Python

- [x] process_data.R: export processed data

- [x] eda_graffiti.R: export eda figure and table to results directory

- [x] analysis.R: conduct analysis and export figure to results directory

- [x] report.Rmd: combine the previous figures and data to report the finding

- [x] Update README.md with the new dependency and link the report

- [x] Add bibliography file and reference it in README.md and also report.Rmd (see lecture 3 notes and videos)

- [x] Close all enhancement issues for milestone 2

Requirement see here: https://github.ubc.ca/MDS-2020-21/DSCI_522_dsci-workflows_students/blob/master/release/milestone2/milestone2.md
