### ISSUE TITLE
Milestone 1 Todo list

### ISSUE THREAD

**Issue by KangboLu** [UBC-MDS/DSCI_522_Group_34#2]
Click the blue text to redirect to the requirement for the below task.
**[Project Proposal](https://github.ubc.ca/MDS-2020-21/DSCI_522_dsci-workflows_students/blob/master/release/milestone1/milestone1.md#2-project-proposal):**
- [x] Pick a Dataset 
- [x] Create a Statistic Question

**Project Set up**
- [x] [Create file structure](https://github.ubc.ca/MDS-2020-21/DSCI_522_dsci-workflows_students/blob/master/release/milestone1/milestone1.md#1-project-set-up)

**Documentation:**
- [x] Create "[Team work contract](https://github.ubc.ca/MDS-2020-21/DSCI_522_dsci-workflows_students/blob/master/release/milestone1/milestone1.md#i-team-work-contract)" file
- [x] Create "[Code of Conduct file](https://github.ubc.ca/MDS-2020-21/DSCI_522_dsci-workflows_students/blob/master/release/milestone1/milestone1.md#ii-code-of-conduct-file)" file
- [x] Create "[Contributing file](https://github.ubc.ca/MDS-2020-21/DSCI_522_dsci-workflows_students/blob/master/release/milestone1/milestone1.md#iii-contributing-file)" file
- [x] Create "[License file](https://github.ubc.ca/MDS-2020-21/DSCI_522_dsci-workflows_students/blob/master/release/milestone1/milestone1.md#iv-license-file)" file
- [x] Update "README.md" file with project proposal contents

**Coding:**
- [x] Create a [script for download dataset](https://github.ubc.ca/MDS-2020-21/DSCI_522_dsci-workflows_students/blob/master/release/milestone1/milestone1.md#3-a-script-that-downloads-and-saves-the-data) from public URL
- [x] Write [Exploratory Data Analysis](https://github.ubc.ca/MDS-2020-21/DSCI_522_dsci-workflows_students/blob/master/release/milestone1/milestone1.md#4-exploratory-data-analysis-in-a-literate-code-document) in a literate code document 

Please comment below if we missed any task needed for our milestone 1.

**Comment by roycezhou** [comment]
To add on several bullet points related to our repo dev process, 

- Fork the repo and work there and send pull-requests; Assign others to review
- Create meaningful commit msgs as these will be **marked**. 
- Use GitHub ISSUES.
- Create a release on our repo and name it 0.0.1 and Submit the URL to this release on Canvas (FYI [release doc](https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/managing-releases-in-a-repository))

**Comment by roycezhou** [comment]
To add on for **src**:

EDA should be written in .ipynb or .Rmd + a rendered doc (.md or .pdf).
