### ISSUE TITLE
Milestone 3 TODO

### ISSUE THREAD

**Issue by KangboLu** [UBC-MDS/DSCI_522_Group_34#43]
- [x] **Automating the data-analysis pipeline using Make**
Write another script, a Makefile (literally called Makefile), to act as a driver script to rule them all. 
This script should run the others in sequence, hard coding in the appropriate arguments. 
This script should:
1 - live in the project's root directory and be named Makefile
2 - be well documented (using the project README and comments inside the Makefile to explain what it does and how to use it)
3 - have a `all`: target so that you can easily run the entire analysis from top to bottom by running make all at the command line
4 - have a `clean`: target so that you can easily "undo" your analysis by running make clean at the command line

**Double check**
Reference repo: https://github.com/ttimbers/breast_cancer_predictor/tree/v3.0

- [x] Update Usage section for listing how to run the make file in README.md
- [x] The Makefile must be well documented. 
This means comments throughout, readable code, and a brief summary at the top of each file that answers who wrote it, when it was written and what it does. See reference repo's makefile.
- [x] Update project according to TA's feedbacks.
