### ISSUE TITLE
Milestone 4 TODO

### ISSUE THREAD

**Issue by KangboLu** [UBC-MDS/DSCI_522_Group_34#58]
- [x] Dependency diagram of the Makefile
Create a dependency diagram of the Makefile using makefile2graph (Links to an external site.) and include the image in the README.md file in the root of your project.

- [x] Links to an external site.Make your project reproducible (to the max) with Docker

Wrap your project up in a nice fancy Docker container. To do this, you should:

- [x] Write your own Dockerfile: ours will be similar to this [Dockerfile](https://github.com/ttimbers/breast_cancer_predictor/blob/v4.0/Dockerfile)
 (this should include all the software and libraries/packages needed to run your analysis pipeline, but not this project itself - i.e., do not git clone your project repo inside your Dockerfile). 
This Dockerfile should live in the root of your project repository.

- [x] use GitHub Actions:
 to automate the building of your Docker image from your Dockerfile. 
You can use and edit the GitHub Actions workflow file (Links to an external site.) from the gha_docker_build (Links to an external site.) example repository I have created.

Do NOT include any of your data or code in the docker images!

- [x] include instructions in the project README on how to use your project with and without Docker. I envision that your instructions for using it with Docker should go something like this

Milestone 4 reference: https://github.com/ttimbers/breast_cancer_predictor/tree/v4.0
